export const alignContent: string;
export const blurredImg: string;
export const contentText: string;
export const experienceRectangle1: string;
export const experienceRectangle2: string;
export const img: string;
export const moreInfoText: string;
export const subtitle: string;
export const title: string;
